"""Add security fields

Revision ID: 0084c34f9a81
Revises: d66593af7daf
Create Date: 2025-11-09 21:08:59.855654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0084c34f9a81'
down_revision = 'd66593af7daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns without batch mode (SQLite supports ALTER TABLE ADD COLUMN)
    op.add_column('draft_versions', sa.Column('share_token_expires', sa.DateTime(), nullable=True))

    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('api_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('api_token_created', sa.DateTime(), nullable=True))

    # Unique constraints need batch mode in SQLite
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_verification_token', ['verification_token'])
        batch_op.create_unique_constraint('uq_users_reset_token', ['reset_token'])
        batch_op.create_unique_constraint('uq_users_api_token', ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraints first (needs batch mode)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_api_token', type_='unique')
        batch_op.drop_constraint('uq_users_reset_token', type_='unique')
        batch_op.drop_constraint('uq_users_verification_token', type_='unique')

    # Drop columns (SQLite supports this with batch mode)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_token_created')
        batch_op.drop_column('api_token')
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verification_token_expires')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.drop_column('share_token_expires')

    # ### end Alembic commands ###
