"""Initial migration with existing tables

Revision ID: 5b39d34eb14e
Revises: 
Create Date: 2025-06-24 14:06:54.426276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b39d34eb14e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
