"""Add tag column to draft_versions

Revision ID: d66593af7daf
Revises: 5b39d34eb14e
Create Date: 2025-06-24 14:07:05.474725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66593af7daf'
down_revision = '5b39d34eb14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
